# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - csci620-books-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_0af2977115164798848d6939e85f2d7e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_973a55b624f349bd95b8ae5d564d3fb7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_0af2977115164798848d6939e85f2d7e }}/wsmckenz/csci620-app-api:${{ github.sha }}
        context: api

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'csci620-books-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b281f7c2035d44f9a1ab88a83a3afa75 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0af2977115164798848d6939e85f2d7e }}/wsmckenz/csci620-app-api:${{ github.sha }}'
